### ISSUE TITLE
TODO before new version release

### ISSUE THREAD

**Issue by Ansuel** [Ansuel/tch-nginx-gui#441]
- [x] Review advanced reset
- [x] Move advanced reset and gui info to separate modal and cards
- [x] Sync improvement in firmware 2.0
- [x] Move garbage in env to a more appropriate section (a separate config would be the best)
- [x] Fix and rework xdsctl mapper to stop errors with transformer (rework it to use brcm lua library)
- [x] Adds wansensing button and make connection switch accessible only if it's disabled.
- [x] Fix ipv6 handle
- [x] Adds support for reset option on firmware upgrade
- [x] Make firmware upgrade keep the config file by default!
- [x] Adds some check for available space
- [x] Generate stripped tar.gz before coping bz2 to /root
- [x] Fix https://github.com/Ansuel/tch-nginx-gui/issues/494
- [x] Avoid writing bz2 full package to /root (write directly the stripped .gz package)
- [ ] Revert ajax loading (TODO in a future release)
- [x] Fix  "card_html" : "FORBIDDEN"  on relay card

**Comment by kevdagoat** [comment]
Most likely should fix debughelper too :)

**Comment by kevdagoat** [comment]
Let me write a list.

**Comment by kevdagoat** [comment]
This is what I would like to see. It is more from a project Standpoint!
# [checkbox.unchecked] English checks when doing PR’s (maybe use grammarly?)
# [checkbox.unchecked] This should be moved to a team repository, so we can assign tasks and rolls other that “Collabarator”.
# [checkbox.unchecked] Long term: Good documentation of the modem, and how to write code for it. This is so we can hopefully get more people involved in the process.

This is what I would like to see before the next version:
# [checkbox.unchecked] Full overhaul of README.md
# [checkbox.unchecked] A check in rootdevice to see if the modems flash is full, so the modem doesn’t get bricked.

**Comment by FrancYescO** [comment]
i see nothing about debughelper 😅

**Comment by Ghost9090** [comment]
È normale che con firmware 2.0.0 parecchie personalizzazioni sono sparite? Tipo la casella per aggiornare il firmware e modificare i parametri internet?

**Comment by FrancYescO** [comment]
@monreal 8.11 is already out as stable... du you still have the "Bridge not connected" bug?

**Comment by monreal** [comment]
> @monreal 8.11 is already out as stable... do you still have the "Bridge not connected" bug?

It still says 8.10.72 for me after installing the latest GUI.tar.bz2 using CLI (using the commands from README.md)

**Comment by FrancYescO** [comment]
@monreal use the builtin method to check for GUI upgrades (..or the fixed URL in the README)

**Comment by monreal** [comment]
> @monreal use the builtin method to check for GUI upgrades (..or the fixed URL in the README)

Using the GUI upgrade check was not possible with this version, as it still disables the check in bridge mode. So I had to use the CLI. The upgrade resulted in the problem I described in issue 449. Please advice on what I should do next to fix this.

**Comment by Ansuel** [comment]
xdslctl mapper should be fixed now...

A rework to use libbrcm lua module is somehow useless... Waiting for feedback about fix...

**Comment by Ghost9090** [comment]
ora rendi compatibile la gui con il firmware 2.0.0 @Ansuel

**Comment by Ansuel** [comment]
@Ghost9090 stai esagerando comunque... e ripeto finchè non mi si fa una lista completa dei problemi con 2.0.0... io non ne riscontro... il selettore delle impostazioni connessione è nascosto con il wansensing attivo...
l'aggiornamento firmware lo visualizzo correttamente...

**Comment by putipower** [comment]
@FrancYescO si ho provato anche con gli ultimi driver aggiunti ma la porta non viene visualizzata.poco male ,problema di poca importanza.
grazie per il lavoro che fate

**Comment by putipower** [comment]
oggi con la .87 e' comparsa la porta vdsl!!
Profilo VDSL
17a
Porta DSLAM VDSL
20
Chipset DSLAM
Broadcom ( BDCM )
Firmware DSLAM
192.22 ( 0xc016 )

**Comment by Ansuel** [comment]
Can confirm that with this dev build the firmware upgrade will keep most of the configuration save to the gui
Some config can be modified by the default value of the firmware due to conversion script .

**Comment by flywire** [comment]
> About code... This is plain lua and ningx plugin for the web interface...

https://whirlpool.net.au/wiki/super_modder_hack_technicolor_modem

**Comment by Ghost9090** [comment]
@Ansuel * Sync improvement in firmware 2.0?

**Comment by kevdagoat** [comment]
>  A check in rootdevice to see if the modems flash is full, so the modem doesn’t get bricked.

Definitely needs to be addressed

**Comment by kevdagoat** [comment]
@Ansuel Debug Helper?

**Comment by FrancYescO** [comment]
@kevdagoat whats missing/wrong to the debug helper? (it's the 3rd time i'm asking 😅)

**Comment by kevdagoat** [comment]
The generated file doesn’t get downloaded from the web GUI

**Comment by FrancYescO** [comment]
are you sure? i've fixed it a lot of version ago and is still working on last dev

**Comment by kevdagoat** [comment]
Well ok then :)

Haven’t installed dev as I don’t want to brick my modem
